CREATE TABLE IF NOT EXISTS `Movies` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `image_url` TEXT,
    `title` VARCHAR(255) NOT NULL,
    `release_date` DATE NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(`title`)
)